# Generated by Django 5.0 on 2024-03-25 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="committee",
            old_name="id",
            new_name="code",
        ),
    ]
