# Generated by Django 5.0 on 2024-03-26 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0002_rename_id_committee_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="process",
            name="MPs",
        ),
        migrations.RemoveField(
            model_name="process",
            name="club",
        ),
        migrations.RemoveField(
            model_name="process",
            name="createdBy",
        ),
        migrations.AddField(
            model_name="printmodel",
            name="MPs",
            field=models.ManyToManyField(
                blank=True, related_name="prints", to="sejm_app.envoy"
            ),
        ),
        migrations.AddField(
            model_name="printmodel",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prints",
                to="sejm_app.club",
            ),
        ),
        migrations.AddField(
            model_name="printmodel",
            name="createdBy",
            field=models.CharField(
                blank=True,
                choices=[
                    ("posłowie", "Envoys"),
                    ("klub", "Club"),
                    ("prezydium", "Presidium"),
                    ("obywatele", "Citizens"),
                    ("rząd", "Government"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="printmodel",
            name="pages_count",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
