# Generated by Django 5.0 on 2024-03-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0005_process_pagescount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="pagesCount",
            field=models.SmallIntegerField(
                blank=True, default=0, help_text="Number of pages in the document"
            ),
        ),
    ]
