# Generated by Django 5.0 on 2024-03-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0006_alter_process_pagescount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="comments",
            field=models.TextField(default="Brak"),
        ),
        migrations.AlterField(
            model_name="process",
            name="description",
            field=models.TextField(default="Brak"),
        ),
        migrations.AlterField(
            model_name="process",
            name="documentType",
            field=models.CharField(max_length=64),
        ),
    ]
