# Generated by Django 5.0 on 2024-03-27 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0007_alter_process_comments_alter_process_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeSitting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agenda", models.TextField()),
                ("closed", models.BooleanField()),
                ("date", models.DateField()),
                ("num", models.IntegerField()),
                ("remote", models.BooleanField()),
                ("video_id", models.CharField(blank=True, max_length=60)),
                (
                    "committee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sejm_app.committee",
                    ),
                ),
            ],
        ),
    ]
