# Generated by Django 5.0 on 2024-03-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0008_committeesitting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeesitting",
            name="video_id",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
