# Generated by Django 5.0 on 2024-03-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0009_alter_committeesitting_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="committeesitting",
            name="committee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sittings",
                to="sejm_app.committee",
            ),
        ),
    ]
