# Generated by Django 5.0 on 2024-03-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0010_alter_committeesitting_committee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committeemember",
            options={"ordering": ["function"]},
        ),
        migrations.AddField(
            model_name="committeesitting",
            name="prints",
            field=models.ManyToManyField(
                related_name="committee_sittings", to="sejm_app.printmodel"
            ),
        ),
        migrations.AlterField(
            model_name="committeemember",
            name="function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHAIR", "Przewodniczący"),
                    ("VICE_CHAIR", "zastępca przewodniczącego"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
