# Generated by Django 5.0 on 2024-04-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0013_rename_interpolation_reply_interpellation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voting",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ELECTRONIC", "Elektroniczne"),
                    ("TRADITIONAL", "Tradycyjne"),
                    ("ON_LIST", "Na liście"),
                ],
                help_text="Voting kind",
                max_length=16,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="VotingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option", models.CharField(help_text="Option name", max_length=255)),
                ("optionIndex", models.IntegerField(help_text="Option index")),
                ("votes", models.IntegerField(help_text="Number of votes")),
                (
                    "voting",
                    models.ForeignKey(
                        help_text="Voting ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votingOptions",
                        to="sejm_app.voting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voteOption",
                    models.SmallIntegerField(
                        choices=[
                            (0, "No"),
                            (1, "Yes"),
                            (2, "ABSTAIN"),
                            (3, "ABSENT"),
                            (4, "VOTE_VALID"),
                        ],
                        help_text="Vote option",
                    ),
                ),
                (
                    "vote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listVotes",
                        to="sejm_app.vote",
                    ),
                ),
                (
                    "optionIndex",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sejm_app.votingoption",
                    ),
                ),
            ],
        ),
    ]
