# Generated by Django 5.0 on 2024-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0014_alter_voting_kind_votingoption_listvote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="committeesitting",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="envoy",
            options={"ordering": ["lastName"]},
        ),
        migrations.AddField(
            model_name="voting",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APPLICATION", "Wniosek formalny"),
                    ("DRAFT", "Projekt ustawy"),
                ],
                help_text="Voting category",
                max_length=32,
                null=True,
            ),
        ),
    ]
