# Generated by Django 5.0 on 2024-04-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sejm_app",
            "0015_alter_committeesitting_options_alter_envoy_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingoption",
            name="votes",
            field=models.IntegerField(
                blank=True, default=0, help_text="Number of votes", null=True
            ),
        ),
    ]
