# Generated by Django 5.0 on 2024-04-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0016_alter_votingoption_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="vote",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (0, "No"),
                    (1, "Yes"),
                    (2, "ABSTAIN"),
                    (3, "ABSENT"),
                    (4, "VOTE_VALID"),
                ],
                help_text="Vote option",
                null=True,
            ),
        ),
    ]
