# Generated by Django 5.0 on 2024-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0019_alter_voting_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voting",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("APPLICATION", "Wniosek formalny"),
                    ("PRINTS", "Głosowanie druków"),
                    ("WHOLE_PROJECT", "Głosowanie nad całością projektu"),
                    ("AMENDMENT", "Głosowanie nad poprawką"),
                    ("CANDIDATES", "Głosowanie na kandydatów"),
                ],
                help_text="Voting category",
                max_length=32,
                null=True,
            ),
        ),
    ]
