# Generated by Django 5.0 on 2024-04-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sejm_app", "0022_envoy_isfemale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="voting",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="voting",
            name="description",
            field=models.CharField(
                blank=True, help_text="Voting description", max_length=512, null=True
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="title",
            field=models.CharField(
                blank=True, help_text="Voting topic", max_length=512, null=True
            ),
        ),
        migrations.AlterField(
            model_name="voting",
            name="topic",
            field=models.CharField(
                blank=True, help_text="Short voting topic", max_length=512, null=True
            ),
        ),
    ]
