# Generated by Django 5.0 on 2024-05-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sejm_app", "0024_alter_process_printmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="printmodel",
            options={"ordering": ["deliveryDate"]},
        ),
    ]
