# Generated by Django 5.0 on 2024-10-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sejm_app', '0026_alter_process_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printmodel',
            name='id',
            field=models.CharField(editable=False, max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='printmodel',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
