# Generated by Django 5.0 on 2025-01-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sejm_app', '0027_alter_printmodel_id_alter_printmodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voting',
            name='id',
            field=models.BigIntegerField(help_text='Voting ID', primary_key=True, serialize=False),
        ),
    ]
