# Generated by Django 5.0 on 2024-03-25 12:59

import django.db.models.deletion
from django.db import connection, migrations, models


def create_vector_extension(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(create_vector_extension),
        migrations.CreateModel(
            name="ActStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("actsCount", models.IntegerField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("shortName", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Act",
            fields=[
                (
                    "ELI",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("address", models.CharField(max_length=255)),
                ("announcementDate", models.DateField(blank=True, null=True)),
                ("changeDate", models.DateTimeField()),
                ("displayAddress", models.CharField(max_length=255)),
                ("pos", models.IntegerField()),
                ("textHTML", models.BooleanField()),
                ("textPDF", models.BooleanField()),
                ("title", models.CharField(max_length=1024)),
                ("volume", models.IntegerField()),
                ("year", models.IntegerField()),
                ("directives", models.JSONField()),
                ("entryIntoForce", models.DateField(blank=True, null=True)),
                ("inForce", models.CharField(max_length=255)),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eli_app.actstatus",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eli_app.documenttype",
                    ),
                ),
                (
                    "releasedBy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eli_app.institution",
                    ),
                ),
                ("keywords", models.ManyToManyField(to="eli_app.keyword")),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eli_app.publisher",
                    ),
                ),
            ],
        ),
    ]
