# Generated by Django 5.0 on 2024-11-01 20:06

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eli_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('summary', models.TextField(max_length=1024, null=True, verbose_name='AI summary of the document')),
                ('start_char', models.IntegerField(help_text='The starting character position of the section within the act.', null=True)),
                ('end_char', models.IntegerField(help_text='The ending character position of the section within the act.', null=True)),
                ('content', models.TextField(help_text='The text content of the section.', null=True)),
                ('chapters', models.CharField(max_length=255, null=True)),
                ('act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eli_app.act')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
