# Generated by Django 5.0 on 2024-10-18 16:57

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eli_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="act",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                dimensions=1536, null=True, blank=True
            ),
            preserve_default=False,
        ),
    ]
