# Generated by Django 5.0 on 2024-10-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eli_app", "0003_alter_act_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="act",
            name="text_length",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
