# Generated by Django 5.0 on 2024-10-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eli_app", "0004_act_text_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="act",
            name="AI summary of the document",
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="act",
            name="text_length",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Total length of text that was summarized",
            ),
        ),
    ]
