# Generated by Django 5.0 on 2024-10-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eli_app", "0005_act_ai_summary_of_the_document_alter_act_text_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="act",
            name="AI summary of the document",
        ),
        migrations.AddField(
            model_name="act",
            name="summary",
            field=models.TextField(
                max_length=1024, null=True, verbose_name="AI summary of the document"
            ),
        ),
    ]
