# Generated by Django 5.0 on 2024-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
    ]
