# Generated by Django 5.0 on 2024-04-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "Twórca aplikacji"),
                            (1, "Programista"),
                            (2, "Wspierający"),
                            (3, "Wyjątkowo chojny wspierający"),
                        ],
                        default=2,
                    ),
                ),
                ("since", models.CharField(default="YYYY-MM", max_length=7)),
            ],
        ),
    ]
