# Generated by Django 5.0 on 2024-04-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_app", "0002_teammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos"),
        ),
    ]
