# Generated by Django 5.0 on 2024-10-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_app", "0002_alter_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.CharField(default="Admin", max_length=200),
        ),
    ]
