# Generated by Django 5.0 on 2024-10-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_app", "0003_article_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="article",
            name="is_wide",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
