# Generated by Django 5.0 on 2024-05-06 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community_app", "0003_teammember_about_teammember_facebook_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={"ordering": ["-role"]},
        ),
    ]
