# Generated by Django 5.0 on 2024-05-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_app", "0004_alter_teammember_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="badge",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
