# Generated by Django 5.0 on 2024-05-15 16:22

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models

import community_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("community_app", "0005_teammember_badge"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, unique=True)),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=30, null=True, unique=True),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tag",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "get_latest_by": "id",
                "ordering": ["-created_at"],
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={"ordering": ["role"]},
        ),
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="related_articles",
            field=models.ManyToManyField(blank=True, to="community_app.article"),
        ),
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Draft"),
                    (1, "Waiting for approval"),
                    (2, "Published"),
                    (3, "Declined"),
                    (4, "Archived"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="views"),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="body"),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(upload_to=community_app.models.image_upload_to),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=150, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "Twórca aplikacji"),
                    (1, "Programista"),
                    (2, "Wyjątkowo chojny wspierający"),
                    (3, "Wspierający"),
                ],
                default=3,
            ),
        ),
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        unique=True,
                        verbose_name="category name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("index", models.IntegerField(default=0, verbose_name="index")),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community_app.articlecategory",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "category",
                "ordering": ["-index"],
            },
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="community_app.articlecategory",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags that describe this article",
                to="community_app.articletag",
            ),
        ),
    ]
