# Generated by Django 5.0 on 2024-05-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community_app", "0006_articletag_alter_article_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
