# Generated by Django 5.0 on 2024-05-27 20:31

import django.db.models.deletion
from django.db import migrations, models

import community_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("community_app", "0007_teammember_linkedin_url"),
        ("sejm_app", "0024_alter_process_printmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sejm_app.club",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="envoys",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sejm_app.envoy",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                max_length=255, upload_to=community_app.models.image_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
    ]
