# Generated by Django 5.0 on 2024-06-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community_app", "0008_alter_article_club_alter_article_envoys_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teammember",
            options={"ordering": ["-role"]},
        ),
        migrations.RenameField(
            model_name="article",
            old_name="club",
            new_name="clubs",
        ),
    ]
