# Generated by Django 5.0 on 2024-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community_app", "0009_alter_teammember_options_rename_club_article_clubs"),
        ("sejm_app", "0025_alter_printmodel_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="clubs",
        ),
        migrations.RemoveField(
            model_name="article",
            name="envoys",
        ),
        migrations.AddField(
            model_name="article",
            name="clubs",
            field=models.ManyToManyField(blank=True, null=True, to="sejm_app.club"),
        ),
        migrations.AddField(
            model_name="article",
            name="envoys",
            field=models.ManyToManyField(blank=True, null=True, to="sejm_app.envoy"),
        ),
    ]
